'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblBatchRun
    Public Property RunID As Integer
    Public Property LocationId As Nullable(Of Integer)
    Public Property RunDate As Date
    Public Property ValidityFrom As Date
    Public Property ValidityTo As Nullable(Of Date)
    Public Property LegacyID As Nullable(Of Integer)
    Public Property AuditUserID As Integer
    Public Property RunYear As Integer
    Public Property RunMonth As Byte

    Public Overridable Property tblLocations As tblLocations
    Public Overridable Property tblClaim As ICollection(Of tblClaim) = New HashSet(Of tblClaim)

End Class
