'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblHF
    Public Property HfID As Integer
    Public Property HFCode As String
    Public Property HFName As String
    Public Property LegalForm As String
    Public Property HFLevel As String
    Public Property HFSublevel As String
    Public Property HFAddress As String
    Public Property LocationId As Integer
    Public Property Phone As String
    Public Property Fax As String
    Public Property eMail As String
    Public Property HFCareType As String
    Public Property PLServiceID As Nullable(Of Integer)
    Public Property PLItemID As Nullable(Of Integer)
    Public Property AccCode As String
    Public Property OffLine As Boolean
    Public Property ValidityFrom As Date
    Public Property ValidityTo As Nullable(Of Date)
    Public Property LegacyID As Nullable(Of Integer)
    Public Property AuditUserID As Integer
    Public Property RowID As Byte()

    Public Overridable Property tblClaim As ICollection(Of tblClaim) = New HashSet(Of tblClaim)
    Public Overridable Property tblClaimAdmin As ICollection(Of tblClaimAdmin) = New HashSet(Of tblClaimAdmin)
    Public Overridable Property tblLocations As tblLocations
    Public Overridable Property tblPLItems As tblPLItems
    Public Overridable Property tblPLServices As tblPLServices
    Public Overridable Property tblHFCatchment As ICollection(Of tblHFCatchment) = New HashSet(Of tblHFCatchment)
    Public Overridable Property tblHFSublevel As tblHFSublevel
    Public Overridable Property tblInsuree As ICollection(Of tblInsuree) = New HashSet(Of tblInsuree)
    Public Overridable Property tblLegalForms As tblLegalForms

End Class
