'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblHFCatchment
    Public Property HFCatchmentId As Integer
    Public Property HFID As Integer
    Public Property LocationId As Integer
    Public Property Catchment As Nullable(Of Integer)
    Public Property ValidityFrom As Nullable(Of Date)
    Public Property ValidityTo As Nullable(Of Date)
    Public Property LegacyId As Nullable(Of Integer)
    Public Property AuditUserId As Nullable(Of Integer)

    Public Overridable Property tblHF As tblHF
    Public Overridable Property tblLocations As tblLocations

End Class
