'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblHFSublevel
    Public Property HFSublevel As String
    Public Property HFSublevelDesc As String
    Public Property SortOrder As Nullable(Of Integer)
    Public Property AltLanguage As String

    Public Overridable Property tblHF As ICollection(Of tblHF) = New HashSet(Of tblHF)

End Class
