'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblIMISDefaults
    Public Property DefaultID As Integer
    Public Property PolicyRenewalInterval As Nullable(Of Integer)
    Public Property FTPHost As String
    Public Property FTPUser As String
    Public Property FTPPassword As String
    Public Property FTPPort As Nullable(Of Integer)
    Public Property FTPEnrollmentFolder As String
    Public Property AssociatedPhotoFolder As String
    Public Property FTPClaimFolder As String
    Public Property FTPFeedbackFolder As String
    Public Property FTPPolicyRenewalFolder As String
    Public Property FTPPhoneExtractFolder As String
    Public Property FTPOffLineExtractFolder As String
    Public Property AppVersionBackEnd As Nullable(Of Decimal)
    Public Property AppVersionEnquire As Nullable(Of Decimal)
    Public Property AppVersionEnroll As Nullable(Of Decimal)
    Public Property AppVersionRenewal As Nullable(Of Decimal)
    Public Property AppVersionFeedback As Nullable(Of Decimal)
    Public Property AppVersionClaim As Nullable(Of Decimal)
    Public Property OffLineHF As Nullable(Of Integer)
    Public Property WinRarFolder As String
    Public Property DatabaseBackupFolder As String
    Public Property OfflineCHF As Nullable(Of Integer)
    Public Property SMSLink As String
    Public Property SMSIP As String
    Public Property SMSUserName As String
    Public Property SMSPassword As String
    Public Property SMSSource As String
    Public Property SMSDlr As Nullable(Of Integer)
    Public Property SMSType As Nullable(Of Integer)
    Public Property AppVersionFeedbackRenewal As Nullable(Of Decimal)

End Class
