'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblLanguages
    Public Property LanguageCode As String
    Public Property LanguageName As String
    Public Property SortOrder As Nullable(Of Integer)

    Public Overridable Property tblUsers As ICollection(Of tblUsers) = New HashSet(Of tblUsers)

End Class
