'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPLItemsDetail
    Public Property PLItemDetailID As Integer
    Public Property PLItemID As Integer
    Public Property ItemID As Integer
    Public Property PriceOverule As Nullable(Of Decimal)
    Public Property ValidityFrom As Date
    Public Property ValidityTo As Nullable(Of Date)
    Public Property LegacyID As Nullable(Of Integer)
    Public Property AuditUserID As Integer
    Public Property RowID As Byte()

    Public Overridable Property tblItems As tblItems
    Public Overridable Property tblPLItems As tblPLItems

End Class
