'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPolicy
    Public Property PolicyID As Integer
    Public Property PolicyUUID As Guid
    Public Property FamilyID As Integer
    Public Property EnrollDate As Date
    Public Property StartDate As Date
    Public Property EffectiveDate As Nullable(Of Date)
    Public Property ExpiryDate As Nullable(Of Date)
    Public Property PolicyStatus As Nullable(Of Byte)
    Public Property PolicyValue As Nullable(Of Decimal)
    Public Property ProdID As Integer
    Public Property OfficerID As Nullable(Of Integer)
    Public Property PolicyStage As String
    Public Property ValidityFrom As Date
    Public Property ValidityTo As Nullable(Of Date)
    Public Property LegacyID As Nullable(Of Integer)
    Public Property AuditUserID As Integer
    Public Property RowID As Byte()
    Public Property isOffline As Nullable(Of Boolean)
    Private _RenewalOrder As Integer?
    Public Overridable Property tblClaimDedRem As ICollection(Of tblClaimDedRem) = New HashSet(Of tblClaimDedRem)
    Public Overridable Property tblFamilies As tblFamilies
    Public Overridable Property tblInsureePolicy As ICollection(Of tblInsureePolicy) = New HashSet(Of tblInsureePolicy)
    Public Overridable Property tblOfficer As tblOfficer
    Public Overridable Property tblProduct As tblProduct
    Public Overridable Property tblPolicyRenewals As ICollection(Of tblPolicyRenewals) = New HashSet(Of tblPolicyRenewals)
    Public Overridable Property tblPremium As ICollection(Of tblPremium) = New HashSet(Of tblPremium)
    Public Property RenewalOrder() As Integer?
        Get
            Return _RenewalOrder
        End Get
        Set(ByVal value As Integer?)
            _RenewalOrder = value
        End Set
    End Property
End Class
