'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPayerType
    Public Property Code As String
    Public Property PayerType As String
    Public Property AltLanguage As String
    Public Property SortOrder As Nullable(Of Integer)

    Public Overridable Property tblPayer As ICollection(Of tblPayer) = New HashSet(Of tblPayer)

End Class
