'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProduct
    Public Property ProdID As Integer
    Public Property ProdUUID As Guid
    Public Property ProductCode As String
    Public Property ProductName As String
    Public Property LocationId As Nullable(Of Integer)
    Public Property InsurancePeriod As Byte
    Public Property DateFrom As Date
    Public Property DateTo As Date
    Public Property ConversionProdID As Nullable(Of Integer)
    Public Property LumpSum As Decimal
    Public Property MemberCount As Short
    Public Property PremiumAdult As Nullable(Of Decimal)
    Public Property PremiumChild As Nullable(Of Decimal)
    Public Property DedInsuree As Nullable(Of Decimal)
    Public Property DedOPInsuree As Nullable(Of Decimal)
    Public Property DedIPInsuree As Nullable(Of Decimal)
    Public Property MaxInsuree As Nullable(Of Decimal)
    Public Property MaxOPInsuree As Nullable(Of Decimal)
    Public Property MaxIPInsuree As Nullable(Of Decimal)
    Public Property PeriodRelPrices As String
    Public Property PeriodRelPricesOP As String
    Public Property PeriodRelPricesIP As String
    Public Property AccCodePremiums As String
    Public Property AccCodeRemuneration As String
    Public Property DedTreatment As Nullable(Of Decimal)
    Public Property DedOPTreatment As Nullable(Of Decimal)
    Public Property DedIPTreatment As Nullable(Of Decimal)
    Public Property MaxTreatment As Nullable(Of Decimal)
    Public Property MaxOPTreatment As Nullable(Of Decimal)
    Public Property MaxIPTreatment As Nullable(Of Decimal)
    Public Property DedPolicy As Nullable(Of Decimal)
    Public Property DedOPPolicy As Nullable(Of Decimal)
    Public Property DedIPPolicy As Nullable(Of Decimal)
    Public Property MaxPolicy As Nullable(Of Decimal)
    Public Property MaxOPPolicy As Nullable(Of Decimal)
    Public Property MaxIPPolicy As Nullable(Of Decimal)
    Public Property GracePeriod As Integer
    Public Property ValidityFrom As Date
    Public Property ValidityTo As Nullable(Of Date)
    Public Property LegacyID As Nullable(Of Integer)
    Public Property AuditUserID As Integer
    Public Property RowID As Byte()
    Public Property RegistrationLumpSum As Nullable(Of Decimal)
    Public Property RegistrationFee As Nullable(Of Decimal)
    Public Property GeneralAssemblyLumpSum As Nullable(Of Decimal)
    Public Property GeneralAssemblyFee As Nullable(Of Decimal)
    Public Property StartCycle1 As String
    Public Property StartCycle2 As String
    Public Property MaxNoConsultation As Nullable(Of Integer)
    Public Property MaxNoSurgery As Nullable(Of Integer)
    Public Property MaxNoDelivery As Nullable(Of Integer)
    Public Property MaxNoHospitalizaion As Nullable(Of Integer)
    Public Property MaxNoVisits As Nullable(Of Integer)
    Public Property MaxAmountConsultation As Nullable(Of Decimal)
    Public Property MaxAmountSurgery As Nullable(Of Decimal)
    Public Property MaxAmountDelivery As Nullable(Of Decimal)
    Public Property MaxAmountHospitalization As Nullable(Of Decimal)
    Public Property GracePeriodRenewal As Nullable(Of Integer)
    Public Property MaxInstallments As Nullable(Of Integer)
    Public Property WaitingPeriod As Nullable(Of Integer)
    Public Property Threshold As Nullable(Of Integer)
    Public Property RenewalDiscountPerc As Nullable(Of Integer)
    Public Property RenewalDiscountPeriod As Nullable(Of Integer)
    Public Property StartCycle3 As String
    Public Property StartCycle4 As String
    Public Property AdministrationPeriod As Nullable(Of Integer)
    Public Property MaxPolicyExtraMember As Nullable(Of Decimal)
    Public Property MaxPolicyExtraMemberIP As Nullable(Of Decimal)
    Public Property MaxPolicyExtraMemberOP As Nullable(Of Decimal)
    Public Property MaxCeilingPolicy As Nullable(Of Decimal)
    Public Property MaxCeilingPolicyIP As Nullable(Of Decimal)
    Public Property MaxCeilingPolicyOP As Nullable(Of Decimal)
    Public Property EnrolmentDiscountPerc As Nullable(Of Integer)
    Public Property EnrolmentDiscountPeriod As Nullable(Of Integer)
    Public Property MaxAmountAntenatal As Nullable(Of Decimal)
    Public Property MaxNoAntenatal As Nullable(Of Integer)
    Public Property CeilingInterpretation As String

    Public Overridable Property tblCeilingInterpretation As tblCeilingInterpretation
    Public Overridable Property tblClaimItems As ICollection(Of tblClaimItems) = New HashSet(Of tblClaimItems)
    Public Overridable Property tblClaimServices As ICollection(Of tblClaimServices) = New HashSet(Of tblClaimServices)
    Public Overridable Property tblLocations As tblLocations
    Public Overridable Property tblPolicy As ICollection(Of tblPolicy) = New HashSet(Of tblPolicy)
    Public Overridable Property tblPolicyRenewals As ICollection(Of tblPolicyRenewals) = New HashSet(Of tblPolicyRenewals)
    Public Overridable Property tblProduct1 As ICollection(Of tblProduct) = New HashSet(Of tblProduct)
    Public Overridable Property tblProduct2 As tblProduct
    Public Overridable Property tblProductItems As ICollection(Of tblProductItems) = New HashSet(Of tblProductItems)
    Public Overridable Property tblProductServices As ICollection(Of tblProductServices) = New HashSet(Of tblProductServices)
    Public Overridable Property tblRelDistr As ICollection(Of tblRelDistr) = New HashSet(Of tblRelDistr)
    Public Overridable Property tblRelIndex As ICollection(Of tblRelIndex) = New HashSet(Of tblRelIndex)

End Class
