'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblRelations
    Public Property RelationId As Short
    Public Property Relation As String
    Public Property SortOrder As Nullable(Of Integer)
    Public Property AltLanguage As String

    Public Overridable Property tblInsuree As ICollection(Of tblInsuree) = New HashSet(Of tblInsuree)

End Class
