'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class uvwExpenditureInsureeRange
    Public Property Valuated As Nullable(Of Decimal)
    Public Property Insuree As Integer
    Public Property MonthTime As Nullable(Of Integer)
    Public Property QuarterTime As String
    Public Property YearTime As Nullable(Of Integer)
    Public Property Region As String
    Public Property DistrictName As String
    Public Property ProductCode As String
    Public Property ProductName As String
    Public Property Age As Nullable(Of Integer)
    Public Property Gender As String

End Class
