'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class uvwItemExpenditures
    Public Property ItemExpenditure As Nullable(Of Decimal)
    Public Property MonthTime As Nullable(Of Integer)
    Public Property QuarterTime As String
    Public Property YearTime As Nullable(Of Integer)
    Public Property Region As String
    Public Property DistrictName As String
    Public Property ProductCode As String
    Public Property ProductName As String
    Public Property Age As Nullable(Of Integer)
    Public Property Gender As String
    Public Property ItemType As String
    Public Property ItemCode As String
    Public Property ItemName As String
    Public Property ItemCareType As String
    Public Property HFLevel As String
    Public Property HFCode As String
    Public Property HFName As String
    Public Property VisitType As String
    Public Property ICDCode As String
    Public Property ICDName As String
    Public Property IDistrictName As String
    Public Property WardName As String
    Public Property VillageName As String
    Public Property HFDistrict As String
    Public Property HFRegion As String
    Public Property ProdRegion As String

End Class
