'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class uvwNumberFeedbackSent
    Public Property FeedbackSent As Nullable(Of Integer)
    Public Property MonthTime As Nullable(Of Integer)
    Public Property QuarterTime As String
    Public Property YearTime As Nullable(Of Integer)
    Public Property Region As String
    Public Property DistrictName As String
    Public Property ProductCode As String
    Public Property ProductName As String
    Public Property HFLevel As String
    Public Property HFCode As String
    Public Property HFName As String
    Public Property HFDistrict As String
    Public Property HFRegion As String

End Class
