''Copyright (c) 2016-2017 Swiss Agency for Development and Cooperation (SDC)
''
''The program users must agree to the following terms:
''
''Copyright notices
''This program is free software: you can redistribute it and/or modify it under the terms of the GNU AGPL v3 License as published by the 
''Free Software Foundation, version 3 of the License.
''This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
''MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU AGPL v3 License for more details www.gnu.org.
''
''Disclaimer of Warranty
''There is no warranty for the program, to the extent permitted by applicable law; except when otherwise stated in writing the copyright 
''holders and/or other parties provide the program "as is" without warranty of any kind, either expressed or implied, including, but not 
''limited to, the implied warranties of merchantability and fitness for a particular purpose. The entire risk as to the quality and 
''performance of the program is with you. Should the program prove defective, you assume the cost of all necessary servicing, repair or correction.
''
''Limitation of Liability 
''In no event unless required by applicable law or agreed to in writing will any copyright holder, or any other party who modifies and/or 
''conveys the program as permitted above, be liable to you for damages, including any general, special, incidental or consequential damages 
''arising out of the use or inability to use the program (including but not limited to loss of data or data being rendered inaccurate or losses 
''sustained by you or third parties or a failure of the program to operate with any other programs), even if such holder or other party has been 
''advised of the possibility of such damages.
''
''In case of dispute arising out or in relation to the use of the program, it is subject to the public law of Switzerland. The place of jurisdiction is Berne.
'
' 
'

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
'
Namespace IMISService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getFTPCredentialsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnquireInsureeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCurrentVersionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isUniqueReceiptNoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isValidRenewalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isValidClaimOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isValidFeedbackOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isValidPhoneOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getFeedbacksNewOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getFeedbacksOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getRenewalsNewOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getRenewalsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DiscontinuePolicyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetClaimStatsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFeedbackStatsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRenewalStatsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertPhotoEntryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetEnrolmentStatsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CheckServerPathOperationCompleted As System.Threading.SendOrPostCallback
        
        Private checkAppSettingsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPayersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreatePhoneExtractsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateOfflineExtractOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isValidLoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnrollFamilyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private downloadMasterDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DownloadFamilyDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.IMIS.My.MySettings.Default.IMIS_IMISService_Service1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getFTPCredentialsCompleted As getFTPCredentialsCompletedEventHandler
        
        '''<remarks/>
        Public Event EnquireInsureeCompleted As EnquireInsureeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCurrentVersionCompleted As GetCurrentVersionCompletedEventHandler
        
        '''<remarks/>
        Public Event isUniqueReceiptNoCompleted As isUniqueReceiptNoCompletedEventHandler
        
        '''<remarks/>
        Public Event isValidRenewalCompleted As isValidRenewalCompletedEventHandler
        
        '''<remarks/>
        Public Event isValidClaimCompleted As isValidClaimCompletedEventHandler
        
        '''<remarks/>
        Public Event isValidFeedbackCompleted As isValidFeedbackCompletedEventHandler
        
        '''<remarks/>
        Public Event isValidPhoneCompleted As isValidPhoneCompletedEventHandler
        
        '''<remarks/>
        Public Event getFeedbacksNewCompleted As getFeedbacksNewCompletedEventHandler
        
        '''<remarks/>
        Public Event getFeedbacksCompleted As getFeedbacksCompletedEventHandler
        
        '''<remarks/>
        Public Event getRenewalsNewCompleted As getRenewalsNewCompletedEventHandler
        
        '''<remarks/>
        Public Event getRenewalsCompleted As getRenewalsCompletedEventHandler
        
        '''<remarks/>
        Public Event DiscontinuePolicyCompleted As DiscontinuePolicyCompletedEventHandler
        
        '''<remarks/>
        Public Event GetClaimStatsCompleted As GetClaimStatsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFeedbackStatsCompleted As GetFeedbackStatsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRenewalStatsCompleted As GetRenewalStatsCompletedEventHandler
        
        '''<remarks/>
        Public Event InsertPhotoEntryCompleted As InsertPhotoEntryCompletedEventHandler
        
        '''<remarks/>
        Public Event GetEnrolmentStatsCompleted As GetEnrolmentStatsCompletedEventHandler
        
        '''<remarks/>
        Public Event CheckServerPathCompleted As CheckServerPathCompletedEventHandler
        
        '''<remarks/>
        Public Event checkAppSettingsCompleted As checkAppSettingsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPayersCompleted As GetPayersCompletedEventHandler
        
        '''<remarks/>
        Public Event CreatePhoneExtractsCompleted As CreatePhoneExtractsCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateOfflineExtractCompleted As CreateOfflineExtractCompletedEventHandler
        
        '''<remarks/>
        Public Event isValidLoginCompleted As isValidLoginCompletedEventHandler
        
        '''<remarks/>
        Public Event EnrollFamilyCompleted As EnrollFamilyCompletedEventHandler
        
        '''<remarks/>
        Public Event downloadMasterDataCompleted As downloadMasterDataCompletedEventHandler
        
        '''<remarks/>
        Public Event DownloadFamilyDataCompleted As DownloadFamilyDataCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFTPCredentials", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getFTPCredentials() As String
            Dim results() As Object = Me.Invoke("getFTPCredentials", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getFTPCredentialsAsync()
            Me.getFTPCredentialsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getFTPCredentialsAsync(ByVal userState As Object)
            If (Me.getFTPCredentialsOperationCompleted Is Nothing) Then
                Me.getFTPCredentialsOperationCompleted = AddressOf Me.OngetFTPCredentialsOperationCompleted
            End If
            Me.InvokeAsync("getFTPCredentials", New Object(-1) {}, Me.getFTPCredentialsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetFTPCredentialsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getFTPCredentialsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getFTPCredentialsCompleted(Me, New getFTPCredentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnquireInsuree", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnquireInsuree(ByVal CHFID As String) As String
            Dim results() As Object = Me.Invoke("EnquireInsuree", New Object() {CHFID})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnquireInsureeAsync(ByVal CHFID As String)
            Me.EnquireInsureeAsync(CHFID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnquireInsureeAsync(ByVal CHFID As String, ByVal userState As Object)
            If (Me.EnquireInsureeOperationCompleted Is Nothing) Then
                Me.EnquireInsureeOperationCompleted = AddressOf Me.OnEnquireInsureeOperationCompleted
            End If
            Me.InvokeAsync("EnquireInsuree", New Object() {CHFID}, Me.EnquireInsureeOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnquireInsureeOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnquireInsureeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnquireInsureeCompleted(Me, New EnquireInsureeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentVersion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCurrentVersion(ByVal Field As String) As String
            Dim results() As Object = Me.Invoke("GetCurrentVersion", New Object() {Field})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCurrentVersionAsync(ByVal Field As String)
            Me.GetCurrentVersionAsync(Field, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCurrentVersionAsync(ByVal Field As String, ByVal userState As Object)
            If (Me.GetCurrentVersionOperationCompleted Is Nothing) Then
                Me.GetCurrentVersionOperationCompleted = AddressOf Me.OnGetCurrentVersionOperationCompleted
            End If
            Me.InvokeAsync("GetCurrentVersion", New Object() {Field}, Me.GetCurrentVersionOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCurrentVersionOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCurrentVersionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCurrentVersionCompleted(Me, New GetCurrentVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isUniqueReceiptNo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isUniqueReceiptNo(ByVal ReceiptNo As String, ByVal CHFID As String) As Boolean
            Dim results() As Object = Me.Invoke("isUniqueReceiptNo", New Object() {ReceiptNo, CHFID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isUniqueReceiptNoAsync(ByVal ReceiptNo As String, ByVal CHFID As String)
            Me.isUniqueReceiptNoAsync(ReceiptNo, CHFID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isUniqueReceiptNoAsync(ByVal ReceiptNo As String, ByVal CHFID As String, ByVal userState As Object)
            If (Me.isUniqueReceiptNoOperationCompleted Is Nothing) Then
                Me.isUniqueReceiptNoOperationCompleted = AddressOf Me.OnisUniqueReceiptNoOperationCompleted
            End If
            Me.InvokeAsync("isUniqueReceiptNo", New Object() {ReceiptNo, CHFID}, Me.isUniqueReceiptNoOperationCompleted, userState)
        End Sub
        
        Private Sub OnisUniqueReceiptNoOperationCompleted(ByVal arg As Object)
            If (Not (Me.isUniqueReceiptNoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isUniqueReceiptNoCompleted(Me, New isUniqueReceiptNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isValidRenewal", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isValidRenewal(ByVal FileName As String) As Boolean
            Dim results() As Object = Me.Invoke("isValidRenewal", New Object() {FileName})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isValidRenewalAsync(ByVal FileName As String)
            Me.isValidRenewalAsync(FileName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isValidRenewalAsync(ByVal FileName As String, ByVal userState As Object)
            If (Me.isValidRenewalOperationCompleted Is Nothing) Then
                Me.isValidRenewalOperationCompleted = AddressOf Me.OnisValidRenewalOperationCompleted
            End If
            Me.InvokeAsync("isValidRenewal", New Object() {FileName}, Me.isValidRenewalOperationCompleted, userState)
        End Sub
        
        Private Sub OnisValidRenewalOperationCompleted(ByVal arg As Object)
            If (Not (Me.isValidRenewalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isValidRenewalCompleted(Me, New isValidRenewalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isValidClaim", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isValidClaim(ByVal FileName As String) As Boolean
            Dim results() As Object = Me.Invoke("isValidClaim", New Object() {FileName})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isValidClaimAsync(ByVal FileName As String)
            Me.isValidClaimAsync(FileName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isValidClaimAsync(ByVal FileName As String, ByVal userState As Object)
            If (Me.isValidClaimOperationCompleted Is Nothing) Then
                Me.isValidClaimOperationCompleted = AddressOf Me.OnisValidClaimOperationCompleted
            End If
            Me.InvokeAsync("isValidClaim", New Object() {FileName}, Me.isValidClaimOperationCompleted, userState)
        End Sub
        
        Private Sub OnisValidClaimOperationCompleted(ByVal arg As Object)
            If (Not (Me.isValidClaimCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isValidClaimCompleted(Me, New isValidClaimCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isValidFeedback", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isValidFeedback(ByVal FileName As String) As Boolean
            Dim results() As Object = Me.Invoke("isValidFeedback", New Object() {FileName})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isValidFeedbackAsync(ByVal FileName As String)
            Me.isValidFeedbackAsync(FileName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isValidFeedbackAsync(ByVal FileName As String, ByVal userState As Object)
            If (Me.isValidFeedbackOperationCompleted Is Nothing) Then
                Me.isValidFeedbackOperationCompleted = AddressOf Me.OnisValidFeedbackOperationCompleted
            End If
            Me.InvokeAsync("isValidFeedback", New Object() {FileName}, Me.isValidFeedbackOperationCompleted, userState)
        End Sub
        
        Private Sub OnisValidFeedbackOperationCompleted(ByVal arg As Object)
            If (Not (Me.isValidFeedbackCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isValidFeedbackCompleted(Me, New isValidFeedbackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isValidPhone", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isValidPhone(ByVal OfficerCode As String, ByVal PhoneNumber As String) As Boolean
            Dim results() As Object = Me.Invoke("isValidPhone", New Object() {OfficerCode, PhoneNumber})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isValidPhoneAsync(ByVal OfficerCode As String, ByVal PhoneNumber As String)
            Me.isValidPhoneAsync(OfficerCode, PhoneNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isValidPhoneAsync(ByVal OfficerCode As String, ByVal PhoneNumber As String, ByVal userState As Object)
            If (Me.isValidPhoneOperationCompleted Is Nothing) Then
                Me.isValidPhoneOperationCompleted = AddressOf Me.OnisValidPhoneOperationCompleted
            End If
            Me.InvokeAsync("isValidPhone", New Object() {OfficerCode, PhoneNumber}, Me.isValidPhoneOperationCompleted, userState)
        End Sub
        
        Private Sub OnisValidPhoneOperationCompleted(ByVal arg As Object)
            If (Not (Me.isValidPhoneCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isValidPhoneCompleted(Me, New isValidPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFeedbacksNew", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getFeedbacksNew(ByVal OfficerCode As String) As String
            Dim results() As Object = Me.Invoke("getFeedbacksNew", New Object() {OfficerCode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getFeedbacksNewAsync(ByVal OfficerCode As String)
            Me.getFeedbacksNewAsync(OfficerCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getFeedbacksNewAsync(ByVal OfficerCode As String, ByVal userState As Object)
            If (Me.getFeedbacksNewOperationCompleted Is Nothing) Then
                Me.getFeedbacksNewOperationCompleted = AddressOf Me.OngetFeedbacksNewOperationCompleted
            End If
            Me.InvokeAsync("getFeedbacksNew", New Object() {OfficerCode}, Me.getFeedbacksNewOperationCompleted, userState)
        End Sub
        
        Private Sub OngetFeedbacksNewOperationCompleted(ByVal arg As Object)
            If (Not (Me.getFeedbacksNewCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getFeedbacksNewCompleted(Me, New getFeedbacksNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFeedbacks", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getFeedbacks(ByVal OfficerCode As String, ByVal PhoneNumber As String) As String
            Dim results() As Object = Me.Invoke("getFeedbacks", New Object() {OfficerCode, PhoneNumber})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getFeedbacksAsync(ByVal OfficerCode As String, ByVal PhoneNumber As String)
            Me.getFeedbacksAsync(OfficerCode, PhoneNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getFeedbacksAsync(ByVal OfficerCode As String, ByVal PhoneNumber As String, ByVal userState As Object)
            If (Me.getFeedbacksOperationCompleted Is Nothing) Then
                Me.getFeedbacksOperationCompleted = AddressOf Me.OngetFeedbacksOperationCompleted
            End If
            Me.InvokeAsync("getFeedbacks", New Object() {OfficerCode, PhoneNumber}, Me.getFeedbacksOperationCompleted, userState)
        End Sub
        
        Private Sub OngetFeedbacksOperationCompleted(ByVal arg As Object)
            If (Not (Me.getFeedbacksCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getFeedbacksCompleted(Me, New getFeedbacksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRenewalsNew", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getRenewalsNew(ByVal OfficerCode As String) As String
            Dim results() As Object = Me.Invoke("getRenewalsNew", New Object() {OfficerCode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getRenewalsNewAsync(ByVal OfficerCode As String)
            Me.getRenewalsNewAsync(OfficerCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getRenewalsNewAsync(ByVal OfficerCode As String, ByVal userState As Object)
            If (Me.getRenewalsNewOperationCompleted Is Nothing) Then
                Me.getRenewalsNewOperationCompleted = AddressOf Me.OngetRenewalsNewOperationCompleted
            End If
            Me.InvokeAsync("getRenewalsNew", New Object() {OfficerCode}, Me.getRenewalsNewOperationCompleted, userState)
        End Sub
        
        Private Sub OngetRenewalsNewOperationCompleted(ByVal arg As Object)
            If (Not (Me.getRenewalsNewCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getRenewalsNewCompleted(Me, New getRenewalsNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getRenewals", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getRenewals(ByVal OfficerCode As String, ByVal PhoneNumber As String) As String
            Dim results() As Object = Me.Invoke("getRenewals", New Object() {OfficerCode, PhoneNumber})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getRenewalsAsync(ByVal OfficerCode As String, ByVal PhoneNumber As String)
            Me.getRenewalsAsync(OfficerCode, PhoneNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getRenewalsAsync(ByVal OfficerCode As String, ByVal PhoneNumber As String, ByVal userState As Object)
            If (Me.getRenewalsOperationCompleted Is Nothing) Then
                Me.getRenewalsOperationCompleted = AddressOf Me.OngetRenewalsOperationCompleted
            End If
            Me.InvokeAsync("getRenewals", New Object() {OfficerCode, PhoneNumber}, Me.getRenewalsOperationCompleted, userState)
        End Sub
        
        Private Sub OngetRenewalsOperationCompleted(ByVal arg As Object)
            If (Not (Me.getRenewalsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getRenewalsCompleted(Me, New getRenewalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DiscontinuePolicy", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub DiscontinuePolicy(ByVal RenewalId As Integer)
            Me.Invoke("DiscontinuePolicy", New Object() {RenewalId})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DiscontinuePolicyAsync(ByVal RenewalId As Integer)
            Me.DiscontinuePolicyAsync(RenewalId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DiscontinuePolicyAsync(ByVal RenewalId As Integer, ByVal userState As Object)
            If (Me.DiscontinuePolicyOperationCompleted Is Nothing) Then
                Me.DiscontinuePolicyOperationCompleted = AddressOf Me.OnDiscontinuePolicyOperationCompleted
            End If
            Me.InvokeAsync("DiscontinuePolicy", New Object() {RenewalId}, Me.DiscontinuePolicyOperationCompleted, userState)
        End Sub
        
        Private Sub OnDiscontinuePolicyOperationCompleted(ByVal arg As Object)
            If (Not (Me.DiscontinuePolicyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DiscontinuePolicyCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClaimStats", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetClaimStats(ByVal HFCode As String, ByVal ClaimAdmin As String, ByVal FromDate As Date, ByVal ToDate As String) As String
            Dim results() As Object = Me.Invoke("GetClaimStats", New Object() {HFCode, ClaimAdmin, FromDate, ToDate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetClaimStatsAsync(ByVal HFCode As String, ByVal ClaimAdmin As String, ByVal FromDate As Date, ByVal ToDate As String)
            Me.GetClaimStatsAsync(HFCode, ClaimAdmin, FromDate, ToDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetClaimStatsAsync(ByVal HFCode As String, ByVal ClaimAdmin As String, ByVal FromDate As Date, ByVal ToDate As String, ByVal userState As Object)
            If (Me.GetClaimStatsOperationCompleted Is Nothing) Then
                Me.GetClaimStatsOperationCompleted = AddressOf Me.OnGetClaimStatsOperationCompleted
            End If
            Me.InvokeAsync("GetClaimStats", New Object() {HFCode, ClaimAdmin, FromDate, ToDate}, Me.GetClaimStatsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetClaimStatsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetClaimStatsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetClaimStatsCompleted(Me, New GetClaimStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFeedbackStats", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFeedbackStats(ByVal OfficerCode As String, ByVal FromDate As Date, ByVal ToDate As Date) As String
            Dim results() As Object = Me.Invoke("GetFeedbackStats", New Object() {OfficerCode, FromDate, ToDate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFeedbackStatsAsync(ByVal OfficerCode As String, ByVal FromDate As Date, ByVal ToDate As Date)
            Me.GetFeedbackStatsAsync(OfficerCode, FromDate, ToDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFeedbackStatsAsync(ByVal OfficerCode As String, ByVal FromDate As Date, ByVal ToDate As Date, ByVal userState As Object)
            If (Me.GetFeedbackStatsOperationCompleted Is Nothing) Then
                Me.GetFeedbackStatsOperationCompleted = AddressOf Me.OnGetFeedbackStatsOperationCompleted
            End If
            Me.InvokeAsync("GetFeedbackStats", New Object() {OfficerCode, FromDate, ToDate}, Me.GetFeedbackStatsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFeedbackStatsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFeedbackStatsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFeedbackStatsCompleted(Me, New GetFeedbackStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRenewalStats", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRenewalStats(ByVal OfficerCode As String, ByVal FromDate As Date, ByVal ToDate As Date) As String
            Dim results() As Object = Me.Invoke("GetRenewalStats", New Object() {OfficerCode, FromDate, ToDate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRenewalStatsAsync(ByVal OfficerCode As String, ByVal FromDate As Date, ByVal ToDate As Date)
            Me.GetRenewalStatsAsync(OfficerCode, FromDate, ToDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRenewalStatsAsync(ByVal OfficerCode As String, ByVal FromDate As Date, ByVal ToDate As Date, ByVal userState As Object)
            If (Me.GetRenewalStatsOperationCompleted Is Nothing) Then
                Me.GetRenewalStatsOperationCompleted = AddressOf Me.OnGetRenewalStatsOperationCompleted
            End If
            Me.InvokeAsync("GetRenewalStats", New Object() {OfficerCode, FromDate, ToDate}, Me.GetRenewalStatsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRenewalStatsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRenewalStatsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRenewalStatsCompleted(Me, New GetRenewalStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertPhotoEntry", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub InsertPhotoEntry(ByVal FileName As String, ByVal CHFID As String, ByVal OfficerCode As String)
            Me.Invoke("InsertPhotoEntry", New Object() {FileName, CHFID, OfficerCode})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertPhotoEntryAsync(ByVal FileName As String, ByVal CHFID As String, ByVal OfficerCode As String)
            Me.InsertPhotoEntryAsync(FileName, CHFID, OfficerCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertPhotoEntryAsync(ByVal FileName As String, ByVal CHFID As String, ByVal OfficerCode As String, ByVal userState As Object)
            If (Me.InsertPhotoEntryOperationCompleted Is Nothing) Then
                Me.InsertPhotoEntryOperationCompleted = AddressOf Me.OnInsertPhotoEntryOperationCompleted
            End If
            Me.InvokeAsync("InsertPhotoEntry", New Object() {FileName, CHFID, OfficerCode}, Me.InsertPhotoEntryOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertPhotoEntryOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertPhotoEntryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertPhotoEntryCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEnrolmentStats", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEnrolmentStats(ByVal OfficerCode As String, ByVal FromDate As String, ByVal ToDate As String) As String
            Dim results() As Object = Me.Invoke("GetEnrolmentStats", New Object() {OfficerCode, FromDate, ToDate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEnrolmentStatsAsync(ByVal OfficerCode As String, ByVal FromDate As String, ByVal ToDate As String)
            Me.GetEnrolmentStatsAsync(OfficerCode, FromDate, ToDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEnrolmentStatsAsync(ByVal OfficerCode As String, ByVal FromDate As String, ByVal ToDate As String, ByVal userState As Object)
            If (Me.GetEnrolmentStatsOperationCompleted Is Nothing) Then
                Me.GetEnrolmentStatsOperationCompleted = AddressOf Me.OnGetEnrolmentStatsOperationCompleted
            End If
            Me.InvokeAsync("GetEnrolmentStats", New Object() {OfficerCode, FromDate, ToDate}, Me.GetEnrolmentStatsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEnrolmentStatsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEnrolmentStatsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEnrolmentStatsCompleted(Me, New GetEnrolmentStatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckServerPath", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckServerPath(ByVal PathToGo As String) As String
            Dim results() As Object = Me.Invoke("CheckServerPath", New Object() {PathToGo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CheckServerPathAsync(ByVal PathToGo As String)
            Me.CheckServerPathAsync(PathToGo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CheckServerPathAsync(ByVal PathToGo As String, ByVal userState As Object)
            If (Me.CheckServerPathOperationCompleted Is Nothing) Then
                Me.CheckServerPathOperationCompleted = AddressOf Me.OnCheckServerPathOperationCompleted
            End If
            Me.InvokeAsync("CheckServerPath", New Object() {PathToGo}, Me.CheckServerPathOperationCompleted, userState)
        End Sub
        
        Private Sub OnCheckServerPathOperationCompleted(ByVal arg As Object)
            If (Not (Me.CheckServerPathCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CheckServerPathCompleted(Me, New CheckServerPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkAppSettings", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function checkAppSettings(ByVal SettingName As String) As String
            Dim results() As Object = Me.Invoke("checkAppSettings", New Object() {SettingName})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub checkAppSettingsAsync(ByVal SettingName As String)
            Me.checkAppSettingsAsync(SettingName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub checkAppSettingsAsync(ByVal SettingName As String, ByVal userState As Object)
            If (Me.checkAppSettingsOperationCompleted Is Nothing) Then
                Me.checkAppSettingsOperationCompleted = AddressOf Me.OncheckAppSettingsOperationCompleted
            End If
            Me.InvokeAsync("checkAppSettings", New Object() {SettingName}, Me.checkAppSettingsOperationCompleted, userState)
        End Sub
        
        Private Sub OncheckAppSettingsOperationCompleted(ByVal arg As Object)
            If (Not (Me.checkAppSettingsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent checkAppSettingsCompleted(Me, New checkAppSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPayers", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPayers(ByVal OfficerCode As String) As String
            Dim results() As Object = Me.Invoke("GetPayers", New Object() {OfficerCode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPayersAsync(ByVal OfficerCode As String)
            Me.GetPayersAsync(OfficerCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPayersAsync(ByVal OfficerCode As String, ByVal userState As Object)
            If (Me.GetPayersOperationCompleted Is Nothing) Then
                Me.GetPayersOperationCompleted = AddressOf Me.OnGetPayersOperationCompleted
            End If
            Me.InvokeAsync("GetPayers", New Object() {OfficerCode}, Me.GetPayersOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPayersOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPayersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPayersCompleted(Me, New GetPayersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreatePhoneExtracts", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreatePhoneExtracts(ByVal DistrictId As Integer, ByVal UserId As Integer, ByVal WithInsuree As Boolean) As Boolean
            Dim results() As Object = Me.Invoke("CreatePhoneExtracts", New Object() {DistrictId, UserId, WithInsuree})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreatePhoneExtractsAsync(ByVal DistrictId As Integer, ByVal UserId As Integer, ByVal WithInsuree As Boolean)
            Me.CreatePhoneExtractsAsync(DistrictId, UserId, WithInsuree, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreatePhoneExtractsAsync(ByVal DistrictId As Integer, ByVal UserId As Integer, ByVal WithInsuree As Boolean, ByVal userState As Object)
            If (Me.CreatePhoneExtractsOperationCompleted Is Nothing) Then
                Me.CreatePhoneExtractsOperationCompleted = AddressOf Me.OnCreatePhoneExtractsOperationCompleted
            End If
            Me.InvokeAsync("CreatePhoneExtracts", New Object() {DistrictId, UserId, WithInsuree}, Me.CreatePhoneExtractsOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreatePhoneExtractsOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreatePhoneExtractsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreatePhoneExtractsCompleted(Me, New CreatePhoneExtractsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOfflineExtract", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CreateOfflineExtract(ByVal RegionId As Integer, ByVal DistrictId As Integer, ByVal UserId As Integer, ByVal WithInsuree As Boolean, ByVal ChkFullExtract As Boolean) As Boolean
            Dim results() As Object = Me.Invoke("CreateOfflineExtract", New Object() {RegionId, DistrictId, UserId, WithInsuree, ChkFullExtract})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CreateOfflineExtractAsync(ByVal RegionId As Integer, ByVal DistrictId As Integer, ByVal UserId As Integer, ByVal WithInsuree As Boolean, ByVal ChkFullExtract As Boolean)
            Me.CreateOfflineExtractAsync(RegionId, DistrictId, UserId, WithInsuree, ChkFullExtract, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateOfflineExtractAsync(ByVal RegionId As Integer, ByVal DistrictId As Integer, ByVal UserId As Integer, ByVal WithInsuree As Boolean, ByVal ChkFullExtract As Boolean, ByVal userState As Object)
            If (Me.CreateOfflineExtractOperationCompleted Is Nothing) Then
                Me.CreateOfflineExtractOperationCompleted = AddressOf Me.OnCreateOfflineExtractOperationCompleted
            End If
            Me.InvokeAsync("CreateOfflineExtract", New Object() {RegionId, DistrictId, UserId, WithInsuree, ChkFullExtract}, Me.CreateOfflineExtractOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOfflineExtractOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateOfflineExtractCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateOfflineExtractCompleted(Me, New CreateOfflineExtractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/isValidLogin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isValidLogin(ByVal LoginName As String, ByVal Password As String) As Integer
            Dim results() As Object = Me.Invoke("isValidLogin", New Object() {LoginName, Password})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isValidLoginAsync(ByVal LoginName As String, ByVal Password As String)
            Me.isValidLoginAsync(LoginName, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isValidLoginAsync(ByVal LoginName As String, ByVal Password As String, ByVal userState As Object)
            If (Me.isValidLoginOperationCompleted Is Nothing) Then
                Me.isValidLoginOperationCompleted = AddressOf Me.OnisValidLoginOperationCompleted
            End If
            Me.InvokeAsync("isValidLogin", New Object() {LoginName, Password}, Me.isValidLoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnisValidLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.isValidLoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isValidLoginCompleted(Me, New isValidLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnrollFamily", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnrollFamily(ByVal Family As String, ByVal Insuree As String, ByVal Policy As String, ByVal Premium As String, ByVal OfficerId As Integer, ByVal UserId As Integer) As Integer
            Dim results() As Object = Me.Invoke("EnrollFamily", New Object() {Family, Insuree, Policy, Premium, OfficerId, UserId})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnrollFamilyAsync(ByVal Family As String, ByVal Insuree As String, ByVal Policy As String, ByVal Premium As String, ByVal OfficerId As Integer, ByVal UserId As Integer)
            Me.EnrollFamilyAsync(Family, Insuree, Policy, Premium, OfficerId, UserId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnrollFamilyAsync(ByVal Family As String, ByVal Insuree As String, ByVal Policy As String, ByVal Premium As String, ByVal OfficerId As Integer, ByVal UserId As Integer, ByVal userState As Object)
            If (Me.EnrollFamilyOperationCompleted Is Nothing) Then
                Me.EnrollFamilyOperationCompleted = AddressOf Me.OnEnrollFamilyOperationCompleted
            End If
            Me.InvokeAsync("EnrollFamily", New Object() {Family, Insuree, Policy, Premium, OfficerId, UserId}, Me.EnrollFamilyOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnrollFamilyOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnrollFamilyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnrollFamilyCompleted(Me, New EnrollFamilyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/downloadMasterData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function downloadMasterData() As String
            Dim results() As Object = Me.Invoke("downloadMasterData", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub downloadMasterDataAsync()
            Me.downloadMasterDataAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub downloadMasterDataAsync(ByVal userState As Object)
            If (Me.downloadMasterDataOperationCompleted Is Nothing) Then
                Me.downloadMasterDataOperationCompleted = AddressOf Me.OndownloadMasterDataOperationCompleted
            End If
            Me.InvokeAsync("downloadMasterData", New Object(-1) {}, Me.downloadMasterDataOperationCompleted, userState)
        End Sub
        
        Private Sub OndownloadMasterDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.downloadMasterDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent downloadMasterDataCompleted(Me, New downloadMasterDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadFamilyData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DownloadFamilyData(ByVal CHFID As String, ByVal LocationId As Integer) As String
            Dim results() As Object = Me.Invoke("DownloadFamilyData", New Object() {CHFID, LocationId})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DownloadFamilyDataAsync(ByVal CHFID As String, ByVal LocationId As Integer)
            Me.DownloadFamilyDataAsync(CHFID, LocationId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DownloadFamilyDataAsync(ByVal CHFID As String, ByVal LocationId As Integer, ByVal userState As Object)
            If (Me.DownloadFamilyDataOperationCompleted Is Nothing) Then
                Me.DownloadFamilyDataOperationCompleted = AddressOf Me.OnDownloadFamilyDataOperationCompleted
            End If
            Me.InvokeAsync("DownloadFamilyData", New Object() {CHFID, LocationId}, Me.DownloadFamilyDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnDownloadFamilyDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.DownloadFamilyDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DownloadFamilyDataCompleted(Me, New DownloadFamilyDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub getFTPCredentialsCompletedEventHandler(ByVal sender As Object, ByVal e As getFTPCredentialsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getFTPCredentialsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub EnquireInsureeCompletedEventHandler(ByVal sender As Object, ByVal e As EnquireInsureeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnquireInsureeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub GetCurrentVersionCompletedEventHandler(ByVal sender As Object, ByVal e As GetCurrentVersionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCurrentVersionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub isUniqueReceiptNoCompletedEventHandler(ByVal sender As Object, ByVal e As isUniqueReceiptNoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isUniqueReceiptNoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub isValidRenewalCompletedEventHandler(ByVal sender As Object, ByVal e As isValidRenewalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isValidRenewalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub isValidClaimCompletedEventHandler(ByVal sender As Object, ByVal e As isValidClaimCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isValidClaimCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub isValidFeedbackCompletedEventHandler(ByVal sender As Object, ByVal e As isValidFeedbackCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isValidFeedbackCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub isValidPhoneCompletedEventHandler(ByVal sender As Object, ByVal e As isValidPhoneCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isValidPhoneCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub getFeedbacksNewCompletedEventHandler(ByVal sender As Object, ByVal e As getFeedbacksNewCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getFeedbacksNewCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub getFeedbacksCompletedEventHandler(ByVal sender As Object, ByVal e As getFeedbacksCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getFeedbacksCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub getRenewalsNewCompletedEventHandler(ByVal sender As Object, ByVal e As getRenewalsNewCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getRenewalsNewCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub getRenewalsCompletedEventHandler(ByVal sender As Object, ByVal e As getRenewalsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getRenewalsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub DiscontinuePolicyCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub GetClaimStatsCompletedEventHandler(ByVal sender As Object, ByVal e As GetClaimStatsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetClaimStatsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub GetFeedbackStatsCompletedEventHandler(ByVal sender As Object, ByVal e As GetFeedbackStatsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFeedbackStatsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub GetRenewalStatsCompletedEventHandler(ByVal sender As Object, ByVal e As GetRenewalStatsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRenewalStatsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub InsertPhotoEntryCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub GetEnrolmentStatsCompletedEventHandler(ByVal sender As Object, ByVal e As GetEnrolmentStatsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEnrolmentStatsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub CheckServerPathCompletedEventHandler(ByVal sender As Object, ByVal e As CheckServerPathCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CheckServerPathCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub checkAppSettingsCompletedEventHandler(ByVal sender As Object, ByVal e As checkAppSettingsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class checkAppSettingsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub GetPayersCompletedEventHandler(ByVal sender As Object, ByVal e As GetPayersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPayersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub CreatePhoneExtractsCompletedEventHandler(ByVal sender As Object, ByVal e As CreatePhoneExtractsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreatePhoneExtractsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub CreateOfflineExtractCompletedEventHandler(ByVal sender As Object, ByVal e As CreateOfflineExtractCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateOfflineExtractCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub isValidLoginCompletedEventHandler(ByVal sender As Object, ByVal e As isValidLoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isValidLoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub EnrollFamilyCompletedEventHandler(ByVal sender As Object, ByVal e As EnrollFamilyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnrollFamilyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub downloadMasterDataCompletedEventHandler(ByVal sender As Object, ByVal e As downloadMasterDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class downloadMasterDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub DownloadFamilyDataCompletedEventHandler(ByVal sender As Object, ByVal e As DownloadFamilyDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DownloadFamilyDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
